// packages/bindings/vue/src/CodeEditor.vue
<script setup lang="ts">
import { watch, onMounted, type PropType } from "vue";
import { useEditor, type UseEditorOptions } from "./useEditor";
import { applyTheme, injectBaseStyles, type Theme } from "@teppan/theme";
import type { Extension } from "@teppan/view";

const props = defineProps({
  modelValue: {
    type: String,
    default: "",
  },
  readOnly: {
    type: Boolean,
    default: false,
  },
  tabSize: {
    type: Number,
    default: 2,
  },
  lineNumbers: {
    type: Boolean,
    default: true,
  },
  placeholder: {
    type: String,
    default: "",
  },
  ariaLabel: {
    type: String,
    default: "Code editor",
  },
  height: {
    type: [String, Number] as PropType<string | number>,
    default: "300px",
  },
  theme: {
    type: Object as PropType<Theme>,
    default: undefined,
  },
  extensions: {
    type: Array as PropType<Extension[]>,
    default: () => [],
  },
});

const emit = defineEmits<{
  (e: "update:modelValue", value: string): void;
  (e: "change", value: string): void;
}>();

const editorOptions: UseEditorOptions = {
  initialContent: props.modelValue,
  readonly: props.readOnly,
  tabSize: props.tabSize,
  lineNumbers: props.lineNumbers,
  placeholder: props.placeholder,
  extensions: props.extensions,
  theme: props.theme,
  onChange: (content) => {
    emit("update:modelValue", content);
    emit("change", content);
  },
};

const { containerRef, view, state, setContent } = useEditor(editorOptions);

// Inject base styles on mount
onMounted(() => {
  injectBaseStyles();
});

// Watch for external content changes
watch(
  () => props.modelValue,
  (newValue) => {
    if (state.value && newValue !== state.value.doc) {
      setContent(newValue);
    }
  }
);

// Apply theme when it changes
watch(
  () => props.theme,
  (theme) => {
    if (view.value && theme) {
      applyTheme(view.value.dom, theme);
    }
  },
  { immediate: true }
);

// Update aria-label
watch(
  () => props.ariaLabel,
  (ariaLabel) => {
    if (view.value) {
      view.value.dom.setAttribute("aria-label", ariaLabel);
    }
  }
);

const containerHeight = typeof props.height === "number" ? `${props.height}px` : props.height;
</script>

<template>
  <div
    ref="containerRef"
    class="teppan-vue-container"
    :style="{ height: containerHeight }"
  />
</template>

<style scoped>
.teppan-vue-container {
  width: 100%;
}
</style>

// packages/bindings/svelte/src/CodeEditor.svelte
<script lang="ts">
  import { applyTheme, injectBaseStyles, type Theme } from "@teppan/theme";
  import {
    EditorView,
    type EditorViewConfig,
    type Extension,
  } from "@teppan/view";
  import { onMount, onDestroy } from "svelte";

  interface Props {
    value?: string;
    readOnly?: boolean;
    tabSize?: number;
    lineNumbers?: boolean;
    placeholder?: string;
    ariaLabel?: string;
    height?: string | number;
    theme?: Theme;
    extensions?: Extension[];
    onchange?: (value: string) => void;
  }

  let {
    value = $bindable(""),
    readOnly = false,
    tabSize = 2,
    lineNumbers = true,
    placeholder = "",
    ariaLabel = "Code editor",
    height = "300px",
    theme,
    extensions = [],
    onchange,
  }: Props = $props();

  let containerElement: HTMLDivElement;
  let view: EditorView | null = null;

  onMount(() => {
    injectBaseStyles();

    const config: EditorViewConfig = {
      doc: value,
      parent: containerElement,
      readonly: readOnly,
      placeholder,
      lineNumbers,
      tabSize,
      extensions: [
        ...extensions,
        {
          name: "svelte-binding",
          updateListeners: [
            (update) => {
              if (update.transaction.docChanged) {
                value = update.state.doc;
                onchange?.(update.state.doc);
              }
            },
          ],
        },
      ],
    };

    view = new EditorView(config);

    if (theme) {
      applyTheme(view.dom, theme);
    }

    view.dom.setAttribute("aria-label", ariaLabel);
  });

  onDestroy(() => {
    view?.destroy();
    view = null;
  });

  const getContainerHeight = () =>
    typeof height === "number" ? `${height}px` : height;
</script>

<div
  bind:this={containerElement}
  class="teppan-svelte-container"
  style="height: {getContainerHeight()}"
></div>

<style>
  .teppan-svelte-container {
    width: 100%;
  }
</style>
